#ifndef _FAPI_NR_UE_CONSTANTS_H_
#define _FAPI_NR_UE_CONSTANTS_H_

//  constants defined by specification 38.331
#define FAPI_NR_MAX_NUM_DL_ALLOCATIONS             16
#define FAPI_NR_MAX_NUM_UL_ALLOCATIONS             16
#define FAPI_NR_MAX_NUM_SERVING_CELLS              32
#define FAPI_NR_MAX_NUM_ZP_CSI_RS_RESOURCE_PER_SET 16
#define FAPI_NR_MAX_NUM_CANDIDATE_BEAMS            16
#define FAPI_NR_MAX_RA_OCCASION_PER_CSIRS          64



#define FAPI_NR_RX_PDU_TYPE_MIB 0x01
#define FAPI_NR_RX_PDU_TYPE_SIB 0x02 
#define FAPI_NR_RX_PDU_TYPE_DLSCH 0x03 

#define CCE_REG_MAPPING_TYPE_INTERLEAVED 0x01
#define CCE_REG_MAPPING_TYPE_NON_INTERLEAVED 0x02

#define PRECODER_GRANULARITY_SAME_AS_REG_BUNDLE 0x01
#define PRECODER_GRANULARITY_ALL_CONTIGUOUS_RBS 0x02


#endif