/***** the library-wide header file *****/
#include "../liblfds700_internal.h"

/***** enums *****/
enum lfds700_btree_au_move
{
  LFDS700_BTREE_AU_MOVE_INVALID,
  LFDS700_BTREE_AU_MOVE_SMALLEST_FROM_RIGHT_CHILD,
  LFDS700_BTREE_AU_MOVE_LARGEST_FROM_LEFT_CHILD,
  LFDS700_BTREE_AU_MOVE_GET_PARENT,
  LFDS700_BTREE_AU_MOVE_MOVE_UP_TREE
};

enum lfds700_btree_au_delete_action
{
  LFDS700_BTREE_AU_DELETE_SELF,
  LFDS700_BTREE_AU_DELETE_SELF_REPLACE_WITH_LEFT_CHILD,
  LFDS700_BTREE_AU_DELETE_SELF_REPLACE_WITH_RIGHT_CHILD,
  LFDS700_BTREE_AU_DELETE_MOVE_LEFT
};

/***** private prototypes *****/

