#include <omp.h>
#pragma omp declare simd notinbranch
static inline void nrLDPC_llr2CnProcBuf_BG1_AVX2(t_nrLDPC_lut* p_lut, int8_t* llr, int8_t* cnProcBuf, uint16_t Z) {
 const uint16_t (*lut_circShift_CNG3) [lut_numCnInCnGroups_BG1_R13[0]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[0]]) p_lut->circShift[0];
 const uint16_t (*lut_circShift_CNG4) [lut_numCnInCnGroups_BG1_R13[1]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[1]]) p_lut->circShift[1];
 const uint16_t (*lut_circShift_CNG5) [lut_numCnInCnGroups_BG1_R13[2]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[2]]) p_lut->circShift[2];
 const uint16_t (*lut_circShift_CNG6) [lut_numCnInCnGroups_BG1_R13[3]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[3]]) p_lut->circShift[3];
 const uint16_t (*lut_circShift_CNG7) [lut_numCnInCnGroups_BG1_R13[4]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[4]]) p_lut->circShift[4];
 const uint16_t (*lut_circShift_CNG8) [lut_numCnInCnGroups_BG1_R13[5]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[5]]) p_lut->circShift[5];
 const uint16_t (*lut_circShift_CNG9) [lut_numCnInCnGroups_BG1_R13[6]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[6]]) p_lut->circShift[6];
 const uint16_t (*lut_circShift_CNG10)[lut_numCnInCnGroups_BG1_R13[7]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[7]]) p_lut->circShift[7];
 const uint16_t (*lut_circShift_CNG19)[lut_numCnInCnGroups_BG1_R13[8]] = (uint16_t(*)[lut_numCnInCnGroups_BG1_R13[8]]) p_lut->circShift[8];
 const uint8_t (*lut_posBnInCnProcBuf_CNG3) [lut_numCnInCnGroups_BG1_R13[0]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[0]]) p_lut->posBnInCnProcBuf[0];
 const uint8_t (*lut_posBnInCnProcBuf_CNG4) [lut_numCnInCnGroups_BG1_R13[1]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[1]]) p_lut->posBnInCnProcBuf[1];
 const uint8_t (*lut_posBnInCnProcBuf_CNG5) [lut_numCnInCnGroups_BG1_R13[2]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[2]]) p_lut->posBnInCnProcBuf[2];
 const uint8_t (*lut_posBnInCnProcBuf_CNG6) [lut_numCnInCnGroups_BG1_R13[3]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[3]]) p_lut->posBnInCnProcBuf[3];
 const uint8_t (*lut_posBnInCnProcBuf_CNG7) [lut_numCnInCnGroups_BG1_R13[4]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[4]]) p_lut->posBnInCnProcBuf[4];
 const uint8_t (*lut_posBnInCnProcBuf_CNG8) [lut_numCnInCnGroups_BG1_R13[5]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[5]]) p_lut->posBnInCnProcBuf[5];
 const uint8_t (*lut_posBnInCnProcBuf_CNG9) [lut_numCnInCnGroups_BG1_R13[6]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[6]]) p_lut->posBnInCnProcBuf[6];
 const uint8_t (*lut_posBnInCnProcBuf_CNG10)[lut_numCnInCnGroups_BG1_R13[7]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[7]]) p_lut->posBnInCnProcBuf[7];
 const uint8_t (*lut_posBnInCnProcBuf_CNG19)[lut_numCnInCnGroups_BG1_R13[8]] = (uint8_t(*)[lut_numCnInCnGroups_BG1_R13[8]]) p_lut->posBnInCnProcBuf[8];
                 int8_t* p_cnProcBuf;
                uint32_t  idxBn = 0;
                p_cnProcBuf= &cnProcBuf[0];
                idxBn = lut_posBnInCnProcBuf_CNG3[0][0]*Z;
                nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG3[0][0]);
                p_cnProcBuf= &cnProcBuf[384];
                idxBn = lut_posBnInCnProcBuf_CNG3[1][0]*Z;
                nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG3[1][0]);
                p_cnProcBuf= &cnProcBuf[768];
                idxBn = lut_posBnInCnProcBuf_CNG3[2][0]*Z;
                nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG3[2][0]);
                p_cnProcBuf= &cnProcBuf[1152];
              	idxBn = lut_posBnInCnProcBuf_CNG4[0][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[0][0]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[0][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[0][1]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[0][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[0][2]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[0][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[0][3]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[0][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[0][4]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[3072];
              	idxBn = lut_posBnInCnProcBuf_CNG4[1][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[1][0]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[1][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[1][1]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[1][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[1][2]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[1][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[1][3]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[1][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[1][4]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[4992];
              	idxBn = lut_posBnInCnProcBuf_CNG4[2][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[2][0]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[2][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[2][1]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[2][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[2][2]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[2][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[2][3]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[2][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[2][4]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[6912];
              	idxBn = lut_posBnInCnProcBuf_CNG4[3][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[3][0]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[3][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[3][1]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[3][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[3][2]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[3][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[3][3]);
        	p_cnProcBuf += Z;
              	idxBn = lut_posBnInCnProcBuf_CNG4[3][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG4[3][4]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[8832];
                idxBn = lut_posBnInCnProcBuf_CNG5[0][0]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][0]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][1]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][1]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][2]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][2]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][3]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][3]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][4]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][4]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][5]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][5]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][6]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][6]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][7]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][7]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][8]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][8]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][9]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][9]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][10]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][10]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][11]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][11]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][12]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][12]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][13]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][13]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][14]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][14]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][15]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][15]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][16]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][16]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[0][17]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[0][17]);
        	  p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[15744];
                idxBn = lut_posBnInCnProcBuf_CNG5[1][0]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][0]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][1]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][1]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][2]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][2]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][3]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][3]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][4]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][4]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][5]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][5]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][6]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][6]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][7]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][7]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][8]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][8]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][9]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][9]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][10]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][10]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][11]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][11]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][12]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][12]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][13]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][13]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][14]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][14]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][15]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][15]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][16]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][16]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[1][17]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[1][17]);
        	  p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[22656];
                idxBn = lut_posBnInCnProcBuf_CNG5[2][0]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][0]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][1]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][1]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][2]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][2]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][3]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][3]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][4]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][4]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][5]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][5]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][6]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][6]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][7]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][7]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][8]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][8]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][9]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][9]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][10]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][10]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][11]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][11]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][12]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][12]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][13]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][13]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][14]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][14]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][15]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][15]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][16]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][16]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[2][17]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[2][17]);
        	  p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[29568];
                idxBn = lut_posBnInCnProcBuf_CNG5[3][0]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][0]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][1]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][1]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][2]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][2]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][3]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][3]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][4]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][4]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][5]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][5]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][6]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][6]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][7]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][7]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][8]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][8]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][9]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][9]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][10]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][10]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][11]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][11]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][12]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][12]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][13]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][13]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][14]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][14]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][15]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][15]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][16]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][16]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[3][17]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[3][17]);
        	  p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[36480];
                idxBn = lut_posBnInCnProcBuf_CNG5[4][0]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][0]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][1]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][1]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][2]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][2]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][3]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][3]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][4]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][4]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][5]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][5]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][6]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][6]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][7]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][7]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][8]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][8]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][9]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][9]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][10]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][10]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][11]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][11]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][12]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][12]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][13]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][13]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][14]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][14]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][15]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][15]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][16]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][16]);
        	  p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG5[4][17]*Z;
              nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG5[4][17]);
        	  p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[43392];
               idxBn = lut_posBnInCnProcBuf_CNG6[0][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][0]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][1]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][2]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][3]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][4]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][5]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][5]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][6]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][6]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[0][7]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[0][7]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[46464];
               idxBn = lut_posBnInCnProcBuf_CNG6[1][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][0]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][1]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][2]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][3]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][4]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][5]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][5]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][6]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][6]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[1][7]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[1][7]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[49536];
               idxBn = lut_posBnInCnProcBuf_CNG6[2][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][0]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][1]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][2]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][3]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][4]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][5]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][5]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][6]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][6]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[2][7]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[2][7]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[52608];
               idxBn = lut_posBnInCnProcBuf_CNG6[3][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][0]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][1]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][2]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][3]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][4]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][5]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][5]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][6]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][6]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[3][7]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[3][7]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[55680];
               idxBn = lut_posBnInCnProcBuf_CNG6[4][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][0]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][1]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][2]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][3]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][4]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][5]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][5]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][6]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][6]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[4][7]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[4][7]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[58752];
               idxBn = lut_posBnInCnProcBuf_CNG6[5][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][0]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][1]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][2]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][2]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][3]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][3]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][4]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][4]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][5]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][5]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][6]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][6]);
        	p_cnProcBuf += Z;
               idxBn = lut_posBnInCnProcBuf_CNG6[5][7]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG6[5][7]);
        	p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[61824];
                idxBn = lut_posBnInCnProcBuf_CNG7[0][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[0][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[0][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[0][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[0][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[0][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[0][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[0][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[0][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[0][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[63744];
                idxBn = lut_posBnInCnProcBuf_CNG7[1][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[1][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[1][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[1][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[1][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[1][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[1][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[1][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[1][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[1][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[65664];
                idxBn = lut_posBnInCnProcBuf_CNG7[2][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[2][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[2][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[2][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[2][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[2][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[2][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[2][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[2][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[2][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[67584];
                idxBn = lut_posBnInCnProcBuf_CNG7[3][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[3][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[3][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[3][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[3][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[3][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[3][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[3][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[3][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[3][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[69504];
                idxBn = lut_posBnInCnProcBuf_CNG7[4][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[4][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[4][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[4][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[4][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[4][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[4][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[4][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[4][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[4][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[71424];
                idxBn = lut_posBnInCnProcBuf_CNG7[5][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[5][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[5][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[5][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[5][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[5][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[5][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[5][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[5][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[5][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[73344];
                idxBn = lut_posBnInCnProcBuf_CNG7[6][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[6][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[6][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[6][1]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[6][2]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[6][2]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[6][3]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[6][3]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG7[6][4]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG7[6][4]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[75264];
                idxBn = lut_posBnInCnProcBuf_CNG8[0][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[0][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[0][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[0][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[76032];
                idxBn = lut_posBnInCnProcBuf_CNG8[1][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[1][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[1][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[1][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[76800];
                idxBn = lut_posBnInCnProcBuf_CNG8[2][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[2][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[2][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[2][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[77568];
                idxBn = lut_posBnInCnProcBuf_CNG8[3][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[3][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[3][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[3][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[78336];
                idxBn = lut_posBnInCnProcBuf_CNG8[4][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[4][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[4][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[4][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[79104];
                idxBn = lut_posBnInCnProcBuf_CNG8[5][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[5][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[5][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[5][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[79872];
                idxBn = lut_posBnInCnProcBuf_CNG8[6][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[6][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[6][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[6][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[80640];
                idxBn = lut_posBnInCnProcBuf_CNG8[7][0]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[7][0]);
       		 p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG8[7][1]*Z;
             nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG8[7][1]);
       		 p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[81408];
                idxBn = lut_posBnInCnProcBuf_CNG9[0][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[0][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[0][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[0][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[82176];
                idxBn = lut_posBnInCnProcBuf_CNG9[1][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[1][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[1][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[1][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[82944];
                idxBn = lut_posBnInCnProcBuf_CNG9[2][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[2][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[2][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[2][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[83712];
                idxBn = lut_posBnInCnProcBuf_CNG9[3][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[3][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[3][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[3][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[84480];
                idxBn = lut_posBnInCnProcBuf_CNG9[4][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[4][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[4][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[4][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[85248];
                idxBn = lut_posBnInCnProcBuf_CNG9[5][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[5][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[5][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[5][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[86016];
                idxBn = lut_posBnInCnProcBuf_CNG9[6][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[6][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[6][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[6][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[86784];
                idxBn = lut_posBnInCnProcBuf_CNG9[7][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[7][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[7][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[7][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[87552];
                idxBn = lut_posBnInCnProcBuf_CNG9[8][0]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[8][0]);
		p_cnProcBuf += Z;
                idxBn = lut_posBnInCnProcBuf_CNG9[8][1]*Z;
            nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG9[8][1]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[88320];
		idxBn = lut_posBnInCnProcBuf_CNG10[0][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[0][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[88704];
		idxBn = lut_posBnInCnProcBuf_CNG10[1][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[1][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[89088];
		idxBn = lut_posBnInCnProcBuf_CNG10[2][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[2][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[89472];
		idxBn = lut_posBnInCnProcBuf_CNG10[3][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[3][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[89856];
		idxBn = lut_posBnInCnProcBuf_CNG10[4][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[4][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[90240];
		idxBn = lut_posBnInCnProcBuf_CNG10[5][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[5][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[90624];
		idxBn = lut_posBnInCnProcBuf_CNG10[6][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[6][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[91008];
		idxBn = lut_posBnInCnProcBuf_CNG10[7][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[7][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[91392];
		idxBn = lut_posBnInCnProcBuf_CNG10[8][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[8][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[91776];
		idxBn = lut_posBnInCnProcBuf_CNG10[9][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG10[9][0]);
		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[92160];
		idxBn = lut_posBnInCnProcBuf_CNG19[0][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[0][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[0][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[0][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[0][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[0][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[0][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[0][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[93696];
		idxBn = lut_posBnInCnProcBuf_CNG19[1][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[1][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[1][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[1][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[1][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[1][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[1][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[1][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[95232];
		idxBn = lut_posBnInCnProcBuf_CNG19[2][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[2][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[2][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[2][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[2][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[2][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[2][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[2][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[96768];
		idxBn = lut_posBnInCnProcBuf_CNG19[3][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[3][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[3][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[3][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[3][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[3][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[3][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[3][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[98304];
		idxBn = lut_posBnInCnProcBuf_CNG19[4][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[4][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[4][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[4][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[4][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[4][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[4][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[4][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[99840];
		idxBn = lut_posBnInCnProcBuf_CNG19[5][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[5][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[5][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[5][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[5][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[5][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[5][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[5][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[101376];
		idxBn = lut_posBnInCnProcBuf_CNG19[6][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[6][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[6][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[6][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[6][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[6][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[6][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[6][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[102912];
		idxBn = lut_posBnInCnProcBuf_CNG19[7][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[7][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[7][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[7][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[7][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[7][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[7][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[7][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[104448];
		idxBn = lut_posBnInCnProcBuf_CNG19[8][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[8][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[8][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[8][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[8][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[8][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[8][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[8][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[105984];
		idxBn = lut_posBnInCnProcBuf_CNG19[9][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[9][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[9][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[9][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[9][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[9][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[9][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[9][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[107520];
		idxBn = lut_posBnInCnProcBuf_CNG19[10][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[10][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[10][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[10][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[10][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[10][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[10][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[10][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[109056];
		idxBn = lut_posBnInCnProcBuf_CNG19[11][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[11][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[11][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[11][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[11][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[11][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[11][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[11][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[110592];
		idxBn = lut_posBnInCnProcBuf_CNG19[12][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[12][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[12][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[12][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[12][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[12][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[12][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[12][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[112128];
		idxBn = lut_posBnInCnProcBuf_CNG19[13][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[13][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[13][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[13][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[13][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[13][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[13][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[13][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[113664];
		idxBn = lut_posBnInCnProcBuf_CNG19[14][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[14][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[14][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[14][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[14][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[14][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[14][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[14][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[115200];
		idxBn = lut_posBnInCnProcBuf_CNG19[15][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[15][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[15][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[15][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[15][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[15][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[15][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[15][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[116736];
		idxBn = lut_posBnInCnProcBuf_CNG19[16][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[16][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[16][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[16][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[16][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[16][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[16][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[16][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[118272];
		idxBn = lut_posBnInCnProcBuf_CNG19[17][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[17][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[17][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[17][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[17][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[17][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[17][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[17][3]);
       		p_cnProcBuf += Z;
                p_cnProcBuf= &cnProcBuf[119808];
		idxBn = lut_posBnInCnProcBuf_CNG19[18][0]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[18][0]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[18][1]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[18][1]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[18][2]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[18][2]);
       		p_cnProcBuf += Z;
		idxBn = lut_posBnInCnProcBuf_CNG19[18][3]*Z;
		nrLDPC_circ_memcpy1(p_cnProcBuf, &llr[idxBn], Z, lut_circShift_CNG19[18][3]);
       		p_cnProcBuf += Z;
}
