CC=gcc
CFLAGS=-Wall -g -pthread -DT_TRACER

#CFLAGS += -O3 -ffast-math -fomit-frame-pointer

LIBS=-lX11 -lm

PROG=tracer_remote
OBJS=remote_old.o plot.o database.o gui.o

$(PROG): gui/gui.a $(OBJS)
	$(CC) $(CFLAGS) -o $(PROG) $(OBJS) gui/gui.a $(LIBS)

textlog: remote.o database.o event.o handler.o textlog.o
	$(CC) $(CFLAGS) -o textlog $^

.PHONY: gui/gui.a

gui/gui.a:
	cd gui && make

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f *.o $(PROG) core textlog
	cd gui && make clean
