CC=gcc
CFLAGS=-Wall -g -pthread -DT_TRACER

#CFLAGS += -O3 -ffast-math -fomit-frame-pointer

LIBS += -lrt

PROG=tracer_local
OBJS=local.o forward.o

$(PROG): $(OBJS)
	$(CC) $(CFLAGS) -o $(PROG) $(OBJS) $(LIBS)

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -f *.o $(PROG) core
