#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for RHEL8
#
#---------------------------------------------------------------------

FROM ran-base:latest AS gnb-base

FROM ran-build:latest AS gnb-build

COPY ./libori.so /usr/local/lib

# build AW2S fronthaul lib
WORKDIR /oai-ran
RUN /bin/sh oaienv && \
    cd cmake_targets/ran_build/build && \
    ninja aw2sori_transpro

RUN python3 ./docker/scripts/generateTemplate.py ./docker/scripts/gnb_parameters.yaml && \
    cp /oai-ran/docker/scripts/gnb_entrypoint.sh /oai-ran/docker/scripts/entrypoint.sh

#start from scratch for target executable
FROM registry.access.redhat.com/ubi8/ubi:latest as oai-gnb-aw2s
ENV TZ=Europe/Paris

RUN yum repolist --disablerepo=* && \
    yum update -y && \
    yum install -y --enablerepo="ubi-8-codeready-builder" \
        procps-ng \
        libXpm \
        libX11 \
        atlas \
        lksctp-tools \
        tzdata \
        net-tools \
        iputils \
        python3-pip && \
    pip3 install six && \
    pip3 install requests && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

WORKDIR /opt/oai-gnb-aw2s/bin
COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/nr-softmodem \
    /oai-ran/docker/scripts/entrypoint.sh \
    ./

COPY --from=gnb-build \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/libaw2sori_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc_optim.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc_optim8seg.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc_orig.so \
    /oai-ran/cmake_targets/ran_build/build/libtelnetsrv.so \
    /usr/local/lib/

COPY --from=gnb-base \
    /lib64/libconfig.so.9 \
    /lib64/libforms.so.2 \
    /lib64/libblas.so.3 \
    /lib64/liblapack.so.3 \
    /lib64/liblapacke.so.3 \
    /lib64/

RUN ln -s /usr/local/lib/libaw2sori_transpro.so /usr/local/lib/libthirdparty_transpro.so && \
    ldconfig

# Copy the relevant configuration files for gNB
WORKDIR /opt/oai-gnb-aw2s/etc
COPY --from=gnb-build /oai-ran/docker/etc .

WORKDIR /opt/oai-gnb-aw2s
#EXPOSE 2152/udp  # S1U, GTP/UDP
#EXPOSE 22100/tcp # ?
#EXPOSE 36412/udp # S1C, SCTP/UDP
#EXPOSE 36422/udp # X2C, SCTP/UDP
#EXPOSE 50000/udp # IF5 / ORI (control)
#EXPOSE 50001/udp # IF5 / ECPRI (data)

ENTRYPOINT ["/opt/oai-gnb-aw2s/bin/entrypoint.sh"]
CMD ["/opt/oai-gnb-aw2s/bin/nr-softmodem", "-O", "/opt/oai-gnb-aw2s/etc/gnb.conf"]
