#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for RHEL8
#
#---------------------------------------------------------------------

FROM ran-build:latest AS enb-build

RUN rm -Rf /oai-ran
WORKDIR /oai-ran
COPY . .

#run build_oai to build the target image
RUN /bin/sh oaienv && \ 
    cd cmake_targets && \
    mkdir -p log && \
    ./build_oai --eNB --ninja -w USRP --verbose-ci

RUN python3 ./docker/scripts/generateTemplate.py ./docker/scripts/enb_parameters.yaml && \
    cp /oai-ran/docker/scripts/enb_entrypoint.sh /oai-ran/docker/scripts/entrypoint.sh

#start from scratch for target executable
FROM registry.access.redhat.com/ubi8/ubi:latest as oai-enb
ENV TZ=Europe/Paris

RUN yum update -y && \
    yum install -y --enablerepo="ubi-8-codeready-builder" \
        lksctp-tools \
        nettle \
        tzdata \
        procps-ng \
        atlas \
        python3 \
        python3-pip \
        net-tools \
        iputils \
        iproute \
        libyaml && \
    pip3 install six && \
    pip3 install requests && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

WORKDIR /opt/oai-enb/bin
COPY --from=enb-build \
    /oai-ran/targets/bin/lte-softmodem.Rel15 \
    /oai-ran/docker/scripts/entrypoint.sh \
    ./

WORKDIR /usr/local/lib/
COPY --from=enb-build \
    /oai-ran/targets/bin/liboai_eth_transpro.so.Rel15 \
    /oai-ran/targets/bin/libtcp_bridge_oai.so.Rel15 \
    /oai-ran/targets/bin/librfsimulator.so.Rel15 \
    /oai-ran/targets/bin/liboai_usrpdevif.so.Rel15 \
    /oai-ran/targets/bin/libcoding.so \
    /oai-ran/targets/bin/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_iqplayer.so \
    /usr/local/lib/libprotobuf-c.so.1 \
    ./

COPY --from=enb-build \
    /lib64/libconfig.so.9 \
    /lib64/libblas.so.3 \
    /lib64/liblapack.so.3 \
    /lib64/liblapacke.so.3 \
    /lib64/libboost_chrono.so.1.66.0 \
    /lib64/libboost_date_time.so.1.66.0 \
    /lib64/libboost_filesystem.so.1.66.0 \
    /lib64/libboost_program_options.so.1.66.0 \
    /lib64/libboost_serialization.so.1.66.0 \
    /lib64/libboost_thread.so.1.66.0 \
    /lib64/libboost_system.so.1.66.0 \
    /lib64/libboost_unit_test_framework.so.1.66.0 \
    /lib64/libboost_atomic.so.1.66.0 \
    /lib64/libboost_timer.so.1.66.0 \
    /lib64/libboost_regex.so.1.66.0 \
    /lib64/

# Now we are copying from builder-image the UHD files.
COPY --from=enb-build /usr/local/bin/uhd_find_devices /usr/local/bin
COPY --from=enb-build /usr/local/lib64/libuhd.so.3.15.0 /usr/local/lib64
COPY --from=enb-build /usr/local/lib64/uhd/utils/uhd_images_downloader.py /opt/oai-enb/bin

WORKDIR /usr/local/share/uhd/rfnoc
COPY --from=enb-build /usr/local/share/uhd/rfnoc/ .

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_eth_transpro.so.Rel15 /usr/local/lib/liboai_transpro.so" && \
    /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so.Rel15 /usr/local/lib/liboai_device.so" && \
    /bin/bash -c "ln -s /usr/local/lib/librfsimulator.so.Rel15 /usr/local/lib/librfsimulator.so" && \
    ldconfig

# Copy the relevant configuration files for eNB
WORKDIR /opt/oai-enb/etc
COPY --from=enb-build /oai-ran/docker/etc .

WORKDIR /opt/oai-enb

# 2152 --> S1U, GTP/UDP
# 36412 --> S1C, SCTP/UDP
# 36422 --> X2C, SCTP/UDP
EXPOSE 2152/udp 36412/udp 36422/udp

ENTRYPOINT ["/opt/oai-enb/bin/entrypoint.sh"]
CMD ["/opt/oai-enb/bin/lte-softmodem.Rel15", "-O", "/opt/oai-enb/etc/enb.conf"]
