#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface BUILD service
#   Valid for Ubuntu 18.04
#
#---------------------------------------------------------------------

FROM ran-base:latest AS nr-ue-base

FROM ran-build:latest AS nr-ue-build

RUN cp /oai-ran/docker/scripts/nr_ue_entrypoint.sh /oai-ran/docker/scripts/entrypoint.sh

#start from scratch for target executable
FROM ubuntu:bionic as oai-nr-ue
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        software-properties-common \
        libsctp1 \
        procps \
        tzdata \
        libnettle6 \
        liblapacke \
        libatlas3-base \
        libconfig9 \
        openssl \
        net-tools \
        python \
        python3 \
        python3-six \
        python3-requests \
        libusb-1.0-0 \
        iputils-ping \
        iproute2 \
        iperf \
        libyaml-0-2 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt/oai-nr-ue/bin
COPY --from=nr-ue-build \
    /oai-ran/targets/bin/nr-uesoftmodem.Rel15 \
    /oai-ran/docker/scripts/entrypoint.sh \
    ./

WORKDIR /opt/oai-nr-ue/etc
COPY --from=nr-ue-build /oai-ran/ci-scripts/conf_files/nr-ue-sim.conf .

COPY --from=nr-ue-build \
    /oai-ran/cmake_targets/ran_build/build/liboai_eth_transpro.so \
    /oai-ran/cmake_targets/ran_build/build/libtcp_bridge_oai.so \
    /oai-ran/cmake_targets/ran_build/build/librfsimulator.so \
    /oai-ran/cmake_targets/ran_build/build/liboai_usrpdevif.so \
    /oai-ran/cmake_targets/ran_build/build/libcoding.so \
    /oai-ran/cmake_targets/ran_build/build/libparams_libconfig.so \
    /oai-ran/cmake_targets/ran_build/build/libdfts.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc_optim.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc_optim8seg.so \
    /oai-ran/cmake_targets/ran_build/build/libldpc_orig.so \
    /usr/local/lib/

# Now we are copying from builder-image the UHD files.
COPY --from=nr-ue-base /usr/local/bin/uhd_find_devices /usr/local/bin
COPY --from=nr-ue-base \
     /usr/local/lib/libuhd.so.3.15.0 \
     /usr/local/lib/libprotobuf-c.so.1 \
     /usr/local/lib/
COPY --from=nr-ue-base /usr/local/lib/uhd/utils/uhd_images_downloader.py /opt/oai-nr-ue/bin

COPY --from=nr-ue-base \
    /usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.65.1 \
    /usr/lib/x86_64-linux-gnu/

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so /usr/local/lib/liboai_device.so" && \
    ldconfig

WORKDIR /opt/oai-nr-ue
CMD ["/opt/oai-nr-ue/bin/nr-uesoftmodem.Rel15", "-O", "/opt/oai-nr-ue/etc/nr-ue-sim.conf"]
ENTRYPOINT ["/opt/oai-nr-ue/bin/entrypoint.sh"]
