# SPDX-License-Identifier: LicenseRef-CSSL-1.0

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface RAN Build for FHI 7.2
#               Valid for UBI9
#
#---------------------------------------------------------------------

FROM ran-base:latest AS ran-base
ENV TZ=Europe

RUN rm -Rf /oai-ran
WORKDIR /oai-ran

ARG DPDK_VERSION=22.11.11
ARG xran_VERSION=11.1.7

## Download and build DPDK
RUN wget --no-verbose http://fast.dpdk.org/rel/dpdk-$DPDK_VERSION.tar.xz && \
    tar -xf dpdk-$DPDK_VERSION.tar.xz && \
    cd dpdk-stable-$DPDK_VERSION && \
    meson build && \
    ninja -C build && \
    ninja install -C build

## Build Fronthaul library
RUN git clone https://github.com/openairinterface/o-du-phy.git /opt/phy && \
    cd /opt/phy && \
    git checkout $xran_VERSION &&\
    cd /opt/phy/fhi_lib/lib && \
    WIRELESS_SDK_TOOLCHAIN=gcc RTE_SDK=/oai-ran/dpdk-stable-$DPDK_VERSION/ XRAN_DIR=/opt/phy/fhi_lib make XRAN_LIB_SO=1

COPY . .

FROM ran-base AS ran-build-fhi72
ARG E2AP_VERSION=E2AP_V3
ARG KPM_VERSION=KPM_V3_00

## Build and install OAI
RUN /bin/sh oaienv && \ 
    cd cmake_targets && \
    mkdir -p log && \
    scl enable gcc-toolset-13 "\
    ./build_oai \
      --ninja --gNB \
      --build-lib 'telnetsrv enbscope uescope nrscope' \
      -t oran_fhlib_5g --cmake-opt -Dxran_LOCATION=/opt/phy/fhi_lib/lib \
      --build-e2 --cmake-opt -DKPM_VERSION=$KPM_VERSION --cmake-opt -DE2AP_VERSION=$E2AP_VERSION" &&\
    # Mainly to see if the sanitize option was perfectly executed
    ldd ran_build/build/nr-softmodem && \
    ldd ran_build/build/liboran_fhlib_5g.so && \
    ldd /opt/phy/fhi_lib/lib/build/libxran.so

## Build FlexRIC for SM Models
RUN mkdir -p openair2/E2AP/flexric/build && \
    cd openair2/E2AP/flexric/build && \
    scl enable gcc-toolset-13 "\
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
          -DKPM_VERSION=$KPM_VERSION \
          -DE2AP_VERSION=$E2AP_VERSION .. &&\
    ninja && \
    ninja install"
