#!/bin/bash
#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */

# file indent_source_code
# brief
# author Lionel Gauthier
# company Eurecom
# email: lionel.gauthier@eurecom.fr
#
################################
# include helper functions
################################
THIS_SCRIPT_PATH=$(dirname $(readlink -f $0))
source $THIS_SCRIPT_PATH/build_helper

function main()
{
  local MAX_CODE_LENGTH=200
  local INDENT_SPACES=2          
set_openair_env


  # remove trailing white spaces
  #find $OPENAIR_DIR/openair1   -type f \( -name '*.c' -o -name '*.h' \) -exec sed --in-place 's/[[:space:]]\+$//' {} \+
  #find $OPENAIR_DIR/openair2   -type f \( -name '*.c' -o -name '*.h' \) -exec sed --in-place 's/[[:space:]]\+$//' {} \+
  #find $OPENAIR_DIR/openair3   -type f \( -name '*.c' -o -name '*.h' \) -exec sed --in-place 's/[[:space:]]\+$//' {} \+
  #find $OPENAIR_DIR/openair3 -type f \( -name '*.c' -o -name '*.h' \) -exec sed --in-place 's/[[:space:]]\+$//' {} \+
  #find $OPENAIR_DIR/targets    -type f \( -name '*.c' -o -name '*.h' \) -exec sed --in-place 's/[[:space:]]\+$//' {} \+

# Style google not available on 14.04

  exit 0 
  # will use indent
  command -v astyle >/dev/null 2>&1 || { echo >&2 "astyle required but it's not installed."; sudo apt-get install astyle; }
  astyle  --recursive --convert-tabs --indent=spaces=$INDENT_SPACES --style=kr  --indent-col1-comments --max-code-length=$MAX_CODE_LENGTH \
   $OPENAIR_DIR/openair1/*.h \
   $OPENAIR_DIR/openair1/*.c \
   $OPENAIR_DIR/openair2/*.h \
   $OPENAIR_DIR/openair2/*.c \
   $OPENAIR_DIR/openair3/*.h \
   $OPENAIR_DIR/openair3/*.c \
   $OPENAIR_DIR/openair3/*.h \
   $OPENAIR_DIR/openair3/*.c \
   $OPENAIR_DIR/targets/*.h \
   $OPENAIR_DIR/targets/*.c 
}


main "$@"
