#!/bin/bash

echo "This script stops exmimo2 as it might be transmitting signal by itself if lte-softmodem terminates incorrectly"

if [ "$OPENAIR_DIR" == "" ]; then
  echo "Is the OPENAIR_DIR path set correctly? Exiting now"
  exit
fi
sudo -E bash -c 'echo 3 > /proc/sys/vm/drop_caches'

exmimo_mod=`lsmod |grep openair_rf`
#load the module only if absent to avoid kernel crashes
if [ -z "$exmimo_mod" ]
then
  sudo -E $OPENAIR_DIR/cmake_targets/tools/init_exmimo2
fi

#now we stop the card from transmitting anything
cd $OPENAIR_DIR/targets/bin
sudo -E octave -H --no-gui $OPENAIR_DIR/cmake_targets/tools/exmimo_stop_octave.m

