#!/usr/bin/env python3
"""
ue_manager.py — OAI 4G RFSim UE Generator
==========================================
Generates:
  1. USIM config files → ci_scripts/rfsim4g/conf_files/lteue.usim-ci-ueN.conf
  2. docker-compose.ues.yml → ci_scripts/rfsim4g/docker-compose.ues.yml

Paths are resolved from config.py using __file__, so this script always
writes to the correct location regardless of where you run it from.

Usage (number of UEs):
    uv run ue_manager.py --ues 3
    uv run ue_manager.py --ues 5
"""

import argparse
import os
import re
import sys
from pathlib import Path

import config


# ─── USIM Config Generation ───────────────────────────────────────────────────

def increment_msin(base_msin: str, offset: int) -> str:
    """
    Increment the MSIN string by offset, preserving zero-padding.
    Example: increment_msin("0100000001", 2) → "0100000003"
    """
    return str(int(base_msin) + offset).zfill(len(base_msin))


def read_template() -> str:
    path = Path(config.TEMPLATE_USIM)
    if not path.exists():
        print(f"  ✗ Template not found: {path}")
        print(f"    Expected at: {path.resolve()}")
        sys.exit(1)
    return path.read_text()


def write_usim_conf(template: str, msin: str, index: int):
    """Substitute the MSIN in the template and write to conf_files/."""
    # updated = re.sub(r'(MSIN\s*=\s*")[^"]*(")', rf'\g<1>{msin}\g<2>', template)
    updated = re.sub(
        r'MSIN\s*=\s*"?[^";\s]+"?[ \t]*;?',
        f'MSIN="{msin}";',
        template
    )

    output_path = Path(config.CONF_DIR) / config.ue_usim_conf_filename(index)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(updated)
    print(f"  ✓ {output_path}  (MSIN = {msin})")


# ─── Docker Compose Override Generation ──────────────────────────────────────

def generate_ue_service(index: int, msin: str) -> str:
    return f"""
    oai_ue{index}:
        image: ${{REGISTRY-oaisoftwarealliance/}}${{LTEUE_IMG:-oai-lte-ue}}:${{TAG:-develop}}
        privileged: true
        container_name: {config.ue_container_name(index)}
        networks:
            public_net:
                ipv4_address: {config.ue_docker_ip(index)}
        environment:
            TZ: Europe/Paris
            ASAN_OPTIONS: detect_leaks=0
            USE_ADDITIONAL_OPTIONS: >-
                --rfsim
                -C 2680000000
                -r 25
                --ue-rxgain 140
                --ue-txgain 120
                --rfsimulator.[0].serveraddr {config.ENB_IP}
                --log_config.global_log_options level,nocolor,time
        volumes:
            - {config.CONF_DIR}/{config.ue_usim_conf_filename(index)}:/opt/oai-lte-ue/etc/ue_usim.conf
            - {config.RFSIM_CONF}:/opt/oai-lte-ue/etc/ue.conf
            - {config.UE_BINARY}:/opt/oai-lte-ue/bin/lte-uesoftmodem
            - {config.OAI_ROOT}:/openairinterface5g
        healthcheck:
            test: /bin/bash -c "pgrep lte-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
        # Tunnel IP assigned by SPGW: {config.ue_tunnel_ip(index)}
        # IMSI suffix (MSIN): {msin}
"""


def generate_compose_override(num_ues: int) -> str:
    services = "".join(
        generate_ue_service(i, increment_msin(config.FIRST_MSIN, i))
        for i in range(num_ues)
    )
    return f"""# AUTO-GENERATED by ue_manager.py — DO NOT EDIT BY HAND
# UEs: {num_ues}
#
# Start:
#   docker compose -f docker-compose.yml -f docker-compose.ues.yml up -d
# Stop:
#   docker compose -f docker-compose.yml -f docker-compose.ues.yml down

services:
{services}
networks:
    public_net:
        external: true
        name: rfsim4g-oai-public-net
"""


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate USIM configs and docker-compose override for OAI 4G RFSim"
    )
    parser.add_argument("--ues", type=int, required=True,
                        help=f"Number of UEs to generate (max {config.MAX_UES})")
    args = parser.parse_args()

    if not (1 <= args.ues <= config.MAX_UES):
        print(f"ERROR: --ues must be between 1 and {config.MAX_UES}.")
        print(f"  To support more, increase NB_USERS in the HSS service.")
        sys.exit(1)

    # The compose file is always written next to the base docker-compose.yml
    # resolved via config.py's __file__-anchored paths.
    compose_path = Path(config.COMPOSE_DIR) / "docker-compose.ues.yml"

    print(f"""
╔══════════════════════════════════════════════════════════════╗
║  OAI 4G RFSim — UE Manager                                  ║
╠══════════════════════════════════════════════════════════════╣
║  UEs            : {args.ues:<42} ║
║  USIM conf dir  : {config.CONF_DIR:<42} ║
║  Compose output : {str(compose_path):<42} ║
╚══════════════════════════════════════════════════════════════╝
""")

    print("[Step 1] Generating USIM config files...")
    template = read_template()
    for i in range(args.ues):
        write_usim_conf(template, increment_msin(config.FIRST_MSIN, i), i)

    print(f"\n[Step 2] Writing {compose_path} ...")
    compose_path.write_text(generate_compose_override(args.ues))
    print(f"  ✓ Done")

    print(f"""
╔══════════════════════════════════════════════════════════════╗
║  ✓ Done! Next steps:                                         ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  Start core network:                                         ║
║    docker compose -f docker-compose.yml up -d                ║
║                                                              ║
║  Start {args.ues} UE(s):                                          ║
║    docker compose \\                                          ║
║      -f docker-compose.yml \\                                 ║
║      -f docker-compose.ues.yml up -d                         ║
║                                                              ║
║  Generate traffic:                                           ║
║    uv run traffic_gen.py --ues {args.ues:<29} ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
""")


if __name__ == "__main__":
    main()
