#!/bin/bash
cd "$(dirname "$0")/.." || exit
source oaienv
cd cmake_targets || exit

cmd=(
    ./ran_build/build/lte-softmodem
    -O ../ci-scripts/conf_files/rcc.band7.tm1.nfapi.conf
    --noS1
    "$@"
)

exec sudo -E gdb "$@" --args "${cmd[@]}"
